services:
  bimmanagerportal.webapi:
    image: bimmanagerportal.webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: Presentation/BimManagerPortal.WebApi/Dockerfile

  bimmanagerportal.webassembly:
    image: bimmanagerportal.webassembly
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: Presentation/BimManagerPortal.WebAssembly/Dockerfile

