services:

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: postgre_db
      POSTGRES_USER: postgre_user
      POSTGRES_PASSWORD: postgre_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: bendylot/bimmanagerportal-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5002:8080"
    depends_on:
      - postgres
  web:
    image: bendylot/bimmanagerportal-web:latest
    container_name: bimmanagerportal-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: