# ---------- RUNTIME ----------
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# ---------- BUILD ----------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# очистка NuGet cache (иногда полезно в CI)
RUN dotnet nuget locals all --clear

# копируем csproj (для Docker cache)
COPY src/Presentation/BimManagerPortal.WebApi/BimManagerPortal.WebApi.csproj Presentation/BimManagerPortal.WebApi/
COPY src/Core/BimManagerPortal.Application/BimManagerPortal.Application.csproj Core/BimManagerPortal.Application/
COPY src/Core/BimManagerPortal.Domain/BimManagerPortal.Domain.csproj Core/BimManagerPortal.Domain/
COPY src/Infrastructure/BimManagerPortal.Persistance/BimManagerPortal.Persistance.csproj Infrastructure/BimManagerPortal.Persistance/
COPY src/Shared/BimManagerPortal.Shared/BimManagerPortal.Shared.csproj Shared/BimManagerPortal.Shared/

# restore
RUN dotnet restore Presentation/BimManagerPortal.WebApi/BimManagerPortal.WebApi.csproj

# копируем весь код
COPY . .

WORKDIR /src/src/Presentation/BimManagerPortal.WebApi

# build
RUN dotnet build BimManagerPortal.WebApi.csproj \
    -c $BUILD_CONFIGURATION \
    -o /app/build


# ---------- PUBLISH ----------
FROM build AS publish
ARG BUILD_CONFIGURATION=Release

RUN dotnet publish BimManagerPortal.WebApi.csproj \
    -c $BUILD_CONFIGURATION \
    -o /app/publish \
    /p:UseAppHost=false


# ---------- FINAL ----------
FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "BimManagerPortal.WebApi.dll"]