# ---------- BUILD ----------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
WORKDIR /src/Presentation/BimManagerPortal.WebAssembly
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

# ---------- RUNTIME ----------
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Очищаем стандартные файлы nginx
RUN rm /etc/nginx/conf.d/*

# Копируем результат публикации (именно папку wwwroot)
COPY --from=build /app/publish/wwwroot .

# 3. Копируем ваш конфиг именно в conf.d под именем default.conf
COPY Presentation/BimManagerPortal.WebAssembly/nginx.conf /etc/nginx/conf.d/default.conf

RUN cat /etc/nginx/conf.d/default.conf

# ЯВНО указываем команду запуска Nginx, чтобы переопределить любые старые метаданные
ENTRYPOINT ["nginx", "-g", "daemon off;"]