# ---------- BUILD ----------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
WORKDIR /src/Presentation/BimManagerPortal.WebAssembly
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

# ---------- RUNTIME ----------
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Очищаем стандартные файлы nginx
RUN rm -rf ./*

# Копируем результат публикации (именно папку wwwroot)
COPY --from=build /app/publish/wwwroot .

# ЯВНО указываем команду запуска Nginx, чтобы переопределить любые старые метаданные
ENTRYPOINT ["nginx", "-g", "daemon off;"]