# ---------- BUILD ----------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
WORKDIR /src/Presentation/BimManagerPortal.WebAssembly
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

# ---------- RUNTIME ----------
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Очищаем стандартные файлы nginx
RUN rm /etc/nginx/conf.d/*

# Копируем результат публикации (именно папку wwwroot)
COPY --from=build /app/publish/wwwroot .

RUN printf 'server {\n\
    listen 80;\n\
    location / {\n\
        root /usr/share/nginx/html;\n\
        try_files $uri $uri/ /index.html =404;\n\
    }\n\
    location /api/ {\n\
        proxy_pass http://api:8080/;\n\
        proxy_http_version 1.1;\n\
        proxy_set_header Upgrade $http_upgrade;\n\
        proxy_set_header Connection keep-alive;\n\
        proxy_set_header Host $host;\n\
        proxy_cache_bypass $http_upgrade;\n\
    }\n\
}\n' > /etc/nginx/conf.d/default.conf

RUN cat /etc/nginx/conf.d/default.conf

# ЯВНО указываем команду запуска Nginx, чтобы переопределить любые старые метаданные
ENTRYPOINT ["nginx", "-g", "daemon off;"]