server {
    listen 80;
    
    # Сжатие для быстрой загрузки WASM
    gzip on;
    gzip_types text/plain application/xml text/css application/javascript application/wasm;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html =404;
    }

    location /api/ {
        proxy_pass http://api:8080/; # 'api' - имя сервиса из docker-compose
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}