// <auto-generated />
using System;
using BimManagerPortal.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BimManagerPortal.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323071142_AddPluginConfigurations")]
    partial class AddPluginConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BimManagerPortal.Domain.Entities.BigDataPlugins.PluginBigData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("JsonData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserCreater")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserUpdater")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BigDataPlugins");
                });

            modelBuilder.Entity("BimManagerPortal.Domain.Entities.PluginConfigurations.PluginConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserCreater")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserUpdater")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PluginConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
