name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build WebAPI image
      run: |
        docker build \
        -f Presentation/BimManagerPortal.WebApi/Dockerfile \
        -t ${{ secrets.DOCKER_USER }}/bimmanagerportal-api:latest .


    - name: Build WebAssembly image
      run: |
        docker build \
        -f Presentation/BimManagerPortal.WebAssembly/Dockerfile \
        -t ${{ secrets.DOCKER_USER }}/bimmanagerportal-web:latest .


    - name: Push WebAPI image
      run: docker push ${{ secrets.DOCKER_USER }}/bimmanagerportal-api:latest


    - name: Push WebAssembly image
      run: docker push ${{ secrets.DOCKER_USER }}/bimmanagerportal-web:latest


  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/BimManagerPortal
          docker compose pull
          docker compose up -d
